### ISSUE TITLE
CORS: Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by elf-pavlik** [fkooman/phubble#1]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers

after POST to micropub endpoint, I need access to the *Location* header, possibly also *Link* if shortlink created
http://indiewebcamp.com/micropub#Create

**Comment by fkooman** [comment]
Fixed and deployed on https://phubble.tuxed.net/
